customcheck/urls.py
from django.conf.urls import url
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^reject$', views.CotainerReject, name='reject'),
]

gatecontainercheck/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView,
# )

from customcheck.forms import LoginForm 
from .routers import router


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    
    url(r'^container/', include('customcheck.urls',namespace='container')),
    url(r'^gateout/', include('gateout.urls',namespace='gateout')),
    url(r'^', include('customcheck.urls')),
    url(r'^login/', auth_views.login, {'template_name': 'login.html', 'authentication_form': LoginForm} , name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': '/login'},name='logout'),
    url(r'^api/', include("customcheck.api.urls", namespace='container-api')),
    url(r'^api/gateout', include("gateout.api.urls", namespace='gateout-api')),
    url(r'^api2/', include(router.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gateout/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^$', views.hello_world, name='gateout_list'),
	url(r'^/data$', views.upload, name='upload_data'),
	url(r'^/image$', views.image, name='upload_data'),
]

gateout/urls.py
from django.conf.urls import url
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from .views import ContainerDetailView,ContainerListView,daily
from django.views.decorators.csrf import csrf_exempt,csrf_protect

urlpatterns = [
    url(r'^$', ContainerListView.as_view(), name='list'),
    url(r'^report/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',daily ,name='daily'),
    url(r'^(?P<slug>[-\w]+)/$',ContainerDetailView.as_view(),name='detail'),
    
]

gateout/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.urls import reverse

# Create your models here.
class vessel(models.Model):
	code			= models.CharField(max_length=50,primary_key=True)
	name 			= models.CharField(max_length=50)
	description 	= models.TextField(blank=True, null=True)
	created_date 	= models.DateTimeField(auto_now_add=True)
	modified_date 	= models.DateTimeField(blank=True, null=True,auto_now=True)
	user 			= models.ForeignKey('auth.User',blank=True,null=True)
	def __str__(self):
		return '%s %s' %(self.code,self.name)

class voy(models.Model):
	# voy				= models.CharField(max_length=50,primary_key=True)
	voy				= models.CharField(max_length=50)
	vessel 			= models.ForeignKey(vessel)
	description 	= models.TextField(blank=True, null=True)
	created_date 	= models.DateTimeField(auto_now_add=True)
	modified_date 	= models.DateTimeField(blank=True, null=True,auto_now=True)
	user 			= models.ForeignKey('auth.User',blank=True,null=True)
	def __str__(self):
		return self.voy

class booking(models.Model):
	# booking 		= models.CharField(max_length=50,primary_key=True)
	booking 		= models.CharField(max_length=50)
	line			= models.CharField(max_length=50)
	voy 			= models.ForeignKey(voy)
	description 	= models.TextField(blank=True, null=True)
	created_date 	= models.DateTimeField(auto_now_add=True)
	modified_date 	= models.DateTimeField(blank=True, null=True,auto_now=True)
	user 			= models.ForeignKey('auth.User',blank=True,null=True)
	def __str__(self):
		return self.booking

class container(models.Model):
	number 			= models.CharField(max_length=15)
	slug 			= models.SlugField(unique=True,blank=True, null=True)
	terminal		= models.CharField(max_length=10)
	booking 		= models.ForeignKey(booking)
	order_date		= models.DateTimeField(blank=True, null=True)
	imo1			= models.CharField(max_length=20)
	imo2			= models.CharField(max_length=20)
	move			= models.CharField(max_length=50)
	temperature		= models.CharField(max_length=20)
	pod				= models.CharField(max_length=20)
	size			= models.CharField(max_length=20)
	iso 			= models.CharField(max_length=10)
	plate_id		= models.CharField(max_length=20)
	truck_company 	= models.CharField(max_length=100)
	consignee		= models.CharField(max_length=100)
	seal1			= models.CharField(max_length=50)
	seal2			= models.CharField(max_length=50)
	weight			= models.FloatField(default=0)
	exception		= models.CharField(max_length=100)
	genset			= models.CharField(max_length=100)
	damage			= models.CharField(max_length=200)
	remark			= models.CharField(max_length=200)
	checker			= models.CharField(max_length=100)
	check_date		= models.DateTimeField(blank=True, null=True)
	created_date 	= models.DateTimeField(auto_now_add=True)
	modified_date 	= models.DateTimeField(blank=True, null=True,auto_now=True)
	user 			= models.ForeignKey('auth.User',blank=True,null=True)
	
	class Meta:
		unique_together = ('number','booking')

	def __str__(self):
		return self.number

	def get_absolute_url(self):
		return reverse('gateout:detail', kwargs={'slug': self.slug})

def image_directory_path(instance, filename):
    from datetime import datetime
    today = datetime.now()
    year = today.year
    month = today.month
    day = today.day
    return 'images/%s/%s/%s/%s/%s' % (instance.container.terminal,year,month,day, filename)

def thumbnails_directory_path(instance, filename):
    from datetime import datetime
    today = datetime.now()
    year = today.year
    month = today.month
    day = today.day
    return 'thumbnails/%s/%s/%s/%s/%s' % (instance.container.terminal,year,month,day, filename)

# Support multiple image for each contianer
class container_images(models.Model):
	container 		= models.ForeignKey(container)
	image 			= models.ImageField(upload_to =image_directory_path )
	thumbnails_image= models.ImageField(upload_to =thumbnails_directory_path )
	created_date 	= models.DateTimeField(auto_now_add=True)
	modified_date 	= models.DateTimeField(blank=True, null=True,auto_now=True)
	user 			= models.ForeignKey('auth.User',blank=True,null=True)

	def __str__(self):
		return self.container.number

	def get_image_url(self):
		return self.image.url


# def image_directory_path(instance, filename):
#     # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
#     return 'containers/%Y/%m/%d/{0}/{1}'.format(instance.user.id, filename)
    

def create_container_slug(instance, new_slug=None):
    slug = slugify("%s-%s" %(instance.number, instance.booking))
    if new_slug is not None:
        slug = new_slug
    qs = container.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.count())
        return create_container_slug(instance, new_slug=new_slug)
    return slug


def pre_save_container_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_container_slug(instance)

pre_save.connect(pre_save_container_receiver, sender=container)

gateout/api/views.py
from rest_framework.decorators import api_view
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt,csrf_protect


from django.shortcuts import render,render_to_response
from django.http import HttpResponse, HttpResponseRedirect, Http404
import sys
from django.db.models import Q,F
import json
from django.contrib.auth.models import User
from django.views import View
from gateout.models import vessel,voy,booking,container,container_images

@api_view(['POST','GET'])
@csrf_exempt
def hello_world(request):
	if request.method=='POST':
		print('POST')
	if request.method=='GET':
		print('GET')
	return JsonResponse({"message": "Hello, world!"})


@api_view(['POST'])
@csrf_exempt
def upload(request):
	response_msg = ''
	if request.method=='POST':
		try :
			import datetime

			data = json.loads(request.body.decode("utf-8"))
			# Show all data
			for key in data:
				print (key,data[key])
			# return JsonResponse ({'error':'sds'})
			# ------------
			# Verify Container info
			# Create Vessel
			vessel_obj,created = vessel.objects.get_or_create(code=data['vessel_code'])
			vessel_obj.name = data['vessel_name']
			vessel_obj.save()
			# Create Voy
			voy_obj,created = voy.objects.get_or_create(voy=data['voy'],vessel=vessel_obj)
			# Create Booking
			booking_obj,created = booking.objects.get_or_create(booking=data['booking'],voy=voy_obj)
			booking_obj.line = data['shipping_line']
			booking_obj.save()
			# Create Container
			container_obj,created = container.objects.get_or_create(number=data['container'],booking=booking_obj)
			container_obj.order_date = datetime.datetime.strptime(data['order_date'], "%d/%m/%y %H:%M")
			container_obj.imo1 = data['imo1']
			container_obj.imo2 = data['imo2']
			container_obj.move = data['move']
			container_obj.temperature = data['temperature']
			container_obj.pod = data['pod']
			# container_obj.size = data['size']
			container_obj.terminal = 'LCB1' if data['plate'][:1]=='B' else 'LCMT'
			container_obj.iso = data['iso']
			container_obj.plate_id = data['plate']
			container_obj.truck_company = data['truck_company']
			container_obj.consignee = data['consignee']
			container_obj.seal1 = data['seal1']
			container_obj.seal2 = data['seal2']
			container_obj.weight = float(data['gross_weight'].replace(',',''))
			container_obj.exception = data['exception']
			container_obj.genset = data['genset']
			container_obj.damage = data['damage']
			container_obj.remark = '%s %s' % (data['remark1'],data['remark2'])
			container_obj.checker = data['checker']
			container_obj.check_date = datetime.datetime.strptime(data['check_date'], "%d/%m/%y")
			container_obj.save()
			response_msg={'msg':'successful',
							'successful':True,
							'slug': container_obj.slug,
							'container': container_obj.number}
		except OSError as err:
			response_msg={'msg':"OS error: {0}".format(err),
							'created':False}
		except ValueError:
			response_msg={'msg':"Object of type 'type' is not JSON serializable",
							'created':False}

		except TypeError:
			response_msg={'msg':sys.exc_info()[0],
							'created':False}
		except:
			response_msg={'msg':sys.exc_info()[0],
							'created':False}

	return JsonResponse (response_msg)


@api_view(['POST'])
@csrf_exempt
def image(request):
	# print ('image')
	if request.method=='POST':
		image = request.FILES['image']
		thumbnails = request.FILES['thumbnails']
		slug = request.POST.get('slug', '')
		c = container.objects.get(slug=slug)
		# print(c)
		if c :
			c_image = container_images.objects.create(container=c,
								image=image,
								thumbnails_image=thumbnails)
			# c_image.image = image
			# c_image.thumbnails_image = thumbnails
			# c_image.save()
		print(slug)
		return JsonResponse ({'status':'ok'})

gateout/views.py
# from django.shortcuts import render
from django.shortcuts import render,render_to_response
from django.http import HttpResponse, HttpResponseRedirect, Http404
import sys
from django.db.models import Q,F
import json
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from rest_framework.decorators import api_view
from django.http import JsonResponse
from django.views import View
from .models import vessel,voy,booking,container,container_images


# Create your views here.
# import os
# os.environ['NO_PROXY'] = url
# url = "http://localhost:5000/"
# fin = open('simple_table.pdf', 'rb')
# files = {'file': fin}
# try:
#   r = requests.post(url, files=files)
# 	print r.text
# finally:
# 	fin.close()
# r = requests.post(urls,files=files,data={'slug':'sdsdsd'})

# files = {'image':('image.png',i),
# 'thumbnails':('tum.png',t)}

from django.views.generic import DetailView,CreateView,UpdateView,DeleteView,ListView

# class OperationListView(ListView):
# 	model = Operation

class ContainerDetailView(DetailView):
	model = container

class ContainerListView(ListView):
	model = container
	paginate_by = 30
	template_name = 'gateout.html'

	def get_queryset(self):
		from django.utils import timezone
		import pytz
		query = self.request.GET.get('q')
		if query :
			return container.objects.filter(Q(number__icontains=query)|
				Q(booking__booking__icontains=query)|
				Q(booking__voy__voy__icontains=query)|
				Q(booking__voy__vessel__code__icontains=query)|
				Q(booking__voy__vessel__name__icontains=query)|
				Q(booking__line__icontains=query)|
				Q(plate_id__icontains=query)|
				Q(truck_company__icontains=query)|
				Q(consignee__icontains=query)).order_by('-created_date')
		else:
			to_day = timezone.now().today()
		return container.objects.filter(created_date__year=to_day.year,
										created_date__month=to_day.month,
										created_date__day=to_day.day).order_by('-created_date')

# 

def home(request):
	c = container.objects.all().order_by('-created_date')
	return render(request,
		'gateout.html', {'containers':c})

def daily(request,year,month,day):
	c = container.objects.filter(created_date__year=year,
		created_date__month=month,
		created_date__day=day).order_by('created_date')
	# c = container.objects.all()
	context={
		'object_list' : c,
		'year':year,'month':month,'day':day
		}
	# print(c)
	return render(request,
		'gateout_daily.html',context)

# @api_view(['POST'])
# @csrf_exempt
# def image(request):
# 	# print ('image')
# 	if request.method=='POST':
# 		image = request.FILES['image']
# 		thumbnails = request.FILES['thumbnails']
# 		slug = request.POST.get('slug', '')
# 		c = container.objects.get(slug=slug)
# 		# print(c)
# 		if c :
# 			c_image = container_images.objects.create(container=c,
# 								image=image,
# 								thumbnails_image=thumbnails)
# 			# c_image.image = image
# 			# c_image.thumbnails_image = thumbnails
# 			# c_image.save()
# 		print(slug)
# 		return JsonResponse ({'status':'ok'})


# @api_view(['POST'])
# @csrf_exempt
# def upload(request):
# 	response_msg = ''
# 	if request.method=='POST':
# 		try :
# 			import datetime
# 			data = json.loads(request.body.decode("utf-8"))
# 			# Show all data
# 			for key in data:
# 				print (key,data[key])
# 			# ------------
# 			# Verify Container info
# 			# Create Vessel
# 			vessel_obj,created = vessel.objects.get_or_create(code=data['vessel_code'])
# 			vessel_obj.name = data['vessel_name']
# 			vessel_obj.save()
# 			# Create Voy
# 			voy_obj,created = voy.objects.get_or_create(voy=data['voy'],vessel=vessel_obj)
# 			# Create Booking
# 			booking_obj,created = booking.objects.get_or_create(booking=data['booking'],voy=voy_obj)
# 			booking_obj.line = data['shipping_line']
# 			booking_obj.save()
# 			# Create Container
# 			container_obj,created = container.objects.get_or_create(number=data['container'],booking=booking_obj)
# 			container_obj.order_date = datetime.datetime.strptime(data['order_date'], "%d/%m/%y %H:%M")
# 			container_obj.imo1 = data['imo1']
# 			container_obj.imo2 = data['imo2']
# 			container_obj.move = data['move']
# 			container_obj.temperature = data['temperature']
# 			container_obj.pod = data['pod']
# 			# container_obj.size = data['size']
# 			container_obj.terminal = 'LCB1' if data['plate'][:1]=='B' else 'LCMT'
# 			container_obj.iso = data['iso']
# 			container_obj.plate_id = data['plate']
# 			container_obj.truck_company = data['truck_company']
# 			container_obj.consignee = data['consignee']
# 			container_obj.seal1 = data['seal1']
# 			container_obj.seal2 = data['seal2']
# 			container_obj.weight = float(data['gross_weight'].replace(',',''))
# 			container_obj.exception = data['exception']
# 			container_obj.genset = data['genset']
# 			container_obj.damage = data['damage']
# 			container_obj.remark = '%s %s' % (data['remark1'],data['remark2'])
# 			container_obj.checker = data['checker']
# 			container_obj.check_date = datetime.datetime.strptime(data['check_date'], "%d/%m/%y")
# 			container_obj.save()
# 			response_msg={'msg':'successful',
# 							'successful':True,
# 							'slug': container_obj.slug,
# 							'container': container_obj.number}
# 		except OSError as err:
# 			response_msg={'msg':"OS error: {0}".format(err),
# 							'created':False}
# 		except ValueError:
# 			response_msg={'msg':"Object of type 'type' is not JSON serializable",
# 							'created':False}

# 		except TypeError:
# 			response_msg={'msg':sys.exc_info()[0],
# 							'created':False}
# 		except:
# 			response_msg={'msg':sys.exc_info()[0],
# 							'created':False}

# 	return JsonResponse (response_msg)

templates/base.html
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">








    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

  <script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   
  crossorigin="anonymous"></script>

  <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- <div class="container">
  <div class="row">
    <nav class="navbar navbar-inverse navbar-fixed-top">
 
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Container Custom Check</a>
        </div>
    </nav>
 </div> -->
        



<!--    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Container Custom Check</a>
        </div>

        {% if request.user.is_authenticated %}         
          <a class="navbar-brand navbar-right" href="{% url 'logout' %}">Logout</a>
        {% endif %}

      </div>
    </nav>

   <br> -->


   <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Container Custom Check</a>
        </div>
           {% if request.user.is_authenticated %}         
          <a class="navbar-brand navbar-right" href="{% url 'logout' %}">Logout</a>
        {% endif %}
      </div>
    </nav>


<!-- <div class="container">
  <div class="row">
          
  </div>
</div>
 -->
{% block head %}{% endblock head %}
{% block form_content %}{% endblock form_content %}
  

  </body>

   
  </html>

templates/container.html
{% extends "base.html" %}

{% block title %}Container Check{% endblock title %}

<br>



{% block head %}
<div class="container">
        <div class="row">
        <br>
        
       
            {% if form_type == 'add' %}
                <h3>Container Data Entry 
                 <small>
                <a href="{% url 'container:reject' %}">Reject</a>
            {% else %}
                <h3>Reject Container Data Entry 
                 <small>
                <a href="{% url 'container:home' %}">Home</a>
            {% endif %}
        </small>
        </h3>
    </small>
</div>
{% endblock head %}

{% block form_content %}
<div class="row">
<form action="" method="post">
    {% csrf_token %}
    <!-- {{ form }} -->
    <div class="row">
        <div class="col-xs-6 col-sm-4">
            {% for field in form %}
            
            <!-- <div class="fieldWrapper"> -->
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            <!-- </div><br> -->
            <br>
        	{% endfor %}
            <input type="submit" value="Submit" />
        </div>
    </div>
    
</form>

{% if messages %}
<!-- <ul class="messages"> -->
    {% for message in messages %}
    	{% if message.tags == 'success' %} <h1 class="text-success">{{ message }}</h1> {% endif %}
    	{% if message.tags == 'error' %} <h1 class="text-danger">{{ message }}</h1> {% endif %}
    {% endfor %}
    <!-- {% if message.tags %} class="label label-success" {% endif %} -->
    
<!-- </ul> -->
{% endif %}
</div>
{% endblock form_content %}

templates/gateout.html
{% extends "base.html" %}

{% block title %}GateOut Information{% endblock title %}

<br>



{% block head %}

{% endblock head %}

{% block form_content %}
    <div class="container">
        <div class="row">
            <h3>Gate Out Information</h3>

            <form class='form' method='GET' action='.'>
                        <input type='text' id='search' placeholder="Search container,booking,voy,line,vessel" name="q" value='{{ request.GET.q}}'>
                        <button class='btn btn-default' type='submit'>Search</button>
                        <a href="{% url 'gateout:list'  %}">Clear result</a>
                    </form>

            {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} record(s).
            
            {% if not request.GET.q %}
                -- Data of Today
            {% endif %}
            <div class="row">

                {% for c in object_list %}
                  <div class="col-sm-4 col-md-3">
                    <div class="thumbnail">
                            <a href="{{c.get_absolute_url}}">
                                <img src="{{c.container_images_set.first.thumbnails_image.url}}" alt="...">
                            </a>
                          <div class="caption">
                            <h3><a href="{{c.get_absolute_url}}">{{c}}</a>
                                <small>{{c.terminal}}</small>
                            </h3>

                            <p>
                            <i><small>{{c.created_date}}--{{c.iso}}</small></i><br>
                            {{c.truck_company}}<br>
                            {{c.booking}} ,{{c.booking.line}}<br>
                            {{c.booking.voy}},{{c.booking.voy.vessel}}<br>
                            {{c.plate_id}}
                            </p>
                          </div>
                         

                    </div>
                  </div>
              {% endfor %}
            </div>

            {% if is_paginated %}
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                  </ul>
                {% endif %}


        </div>

        {% if messages %}
        <!-- <ul class="messages"> -->
            {% for message in messages %}
                {% if message.tags == 'success' %} <h1 class="text-success">{{ message }}</h1> {% endif %}
                {% if message.tags == 'error' %} <h1 class="text-danger">{{ message }}</h1> {% endif %}
            {% endfor %}
            <!-- {% if message.tags %} class="label label-success" {% endif %} -->
            
        <!-- </ul> -->
        {% endif %}

    </div>
{% endblock form_content %}

templates/gateout_daily.html
{% extends "base.html" %}

{% block title %}GateOut Information{% endblock title %}

<br>



{% block head %}

{% endblock head %}

{% block form_content %}
    <div class="container">
        <div class="row">
            <h3>Gate Out Information of {{year}}-{{month}}-{{day}}</h3>

            <form class='form' method='GET' action='.'>
                        <input type='text' id='search' placeholder="Search container,booking,voy,line,vessel" name="q" value='{{ request.GET.q}}'>
                        <button class='btn btn-default' type='submit'>Search</button>
                        <a href="{% url 'gateout:list'  %}">Clear result</a>
                    </form>

            {{ object_list.count }} record(s).
            
            {% if not request.GET.q %}
                -- Data of {{year}}-{{month}}-{{day}}
            {% endif %}
            <div class="row">

                {% for c in object_list %}
                  <div class="col-sm-4 col-md-3">
                    <div class="thumbnail">
                            <a href="{{c.get_absolute_url}}">
                                <img src="{{c.container_images_set.first.thumbnails_image.url}}" alt="...">
                            </a>
                          <div class="caption">
                            <h3><a href="{{c.get_absolute_url}}">{{c}}</a>
                                <small>{{c.terminal}}</small>
                            </h3>

                            <p>
                            <i><small>{{c.created_date}}--{{c.iso}}</small></i><br>
                            {{c.truck_company}}<br>
                            {{c.booking}} ,{{c.booking.line}}<br>
                            {{c.booking.voy}},{{c.booking.voy.vessel}}<br>
                            {{c.plate_id}}
                            </p>
                          </div>
                         

                    </div>
                  </div>
              {% endfor %}
            </div>

            {% if is_paginated %}
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                  </ul>
                {% endif %}


        </div>

        {% if messages %}
        <!-- <ul class="messages"> -->
            {% for message in messages %}
                {% if message.tags == 'success' %} <h1 class="text-success">{{ message }}</h1> {% endif %}
                {% if message.tags == 'error' %} <h1 class="text-danger">{{ message }}</h1> {% endif %}
            {% endfor %}
            <!-- {% if message.tags %} class="label label-success" {% endif %} -->
            
        <!-- </ul> -->
        {% endif %}

    </div>
{% endblock form_content %}